Feature/core implementation
okayama-daiki/kindle-daily-deals-notifier pull request #1
Opened 2024-10-13 03:26 UTC by okayama-daiki

2024-10-13 05:07 UTC, hamao0820 requested changes
collyに詳しくないので細かいコメントがメインになりました

2024-10-13 05:07 UTC, hamao0820 commented on main.go
> +	messages := []messaging_api.MessageInterface{}
細かいですけど
```
var messages []messaging_api.MessageInterface{}
```
とした方がよりGoっぽいです.
https://zenn.dev/tbistr/articles/go-code-review-comments-jp#declaring-empty-slices

2024-10-13 05:07 UTC, hamao0820 commented on main.go
>  }
責務が違う気もします

2024-10-13 05:07 UTC, hamao0820 commented on libs/notifier/notifier.go
> +}
それと`log.Fatal`はあまり使わない方が良いです. 明示的に`panic`を呼び出すか, `os.Exit(1)`などを使った方が良いです.
https://zenn.dev/snowcrush/articles/21f28163e067cb

2024-10-13 05:07 UTC, hamao0820 commented on deploy.sh
これは`.gitignore`に追加した方がいいんじゃないかな
それか環境変数を使うようにするか

2024-10-13 05:13 UTC, hamao0820 commented on libs/notifier/notifier.go
> +}
`panic`もできるだけ`main`関数以外では呼ばないようにしてください
https://zenn.dev/tbistr/articles/go-code-review-comments-jp#don%E2%80%99t-panic

2024-10-13 05:24 UTC, okayama-daiki commented on libs/product/product.go
> +	URL  url.URL
0ad256d

2024-10-13 05:25 UTC, okayama-daiki commented on libs/product/product.go
> +func NewProduct(name string, url url.URL) Product {
[0ad256d](https://github.com/okayama-daiki/kindle-daily-deals-notifier/pull/1/commits/0ad256d8d7da0e062aa39c98b3c4abe421c6b949)

2024-10-13 05:26 UTC, okayama-daiki commented on libs/product/product.go
> +func NewProduct(name string, url url.URL) Product {
0ad256d

2024-10-13 05:27 UTC, okayama-daiki commented on main.go
>  }
0ad256d

2024-10-13 05:34 UTC, okayama-daiki commented on libs/crawler/crawler.go
> +		TARGET_URL = "https://www.amazon.co.jp/kindle-dbs/browse?widgetId=ebooks-deals-storefront_KindleDailyDealsStrategy&sourceType=recs"
e6e6379

2024-10-13 05:34 UTC, okayama-daiki commented on main.go
> +	messages := []messaging_api.MessageInterface{}
e6e6379

2024-10-13 05:37 UTC, okayama-daiki commented on main.go
> +	productList, err := crawler.Crawl()
046ed11

2024-10-13 05:37 UTC, okayama-daiki commented on main.go
> +	messages := []messaging_api.MessageInterface{}
e6e6379

2024-10-13 05:39 UTC, okayama-daiki commented on libs/crawler/crawler.go
> +		TARGET_URL = "https://www.amazon.co.jp/kindle-dbs/browse?widgetId=ebooks-deals-storefront_KindleDailyDealsStrategy&sourceType=recs"
e6e6379

2024-10-13 05:43 UTC, okayama-daiki commented on libs/crawler/crawler.go
> +		}
8366c2e

2024-10-13 05:51 UTC, okayama-daiki commented on libs/notifier/notifier.go
> +func Notify(targetId string, messages []messaging_api.MessageInterface) {
7b7139e

2024-10-13 05:51 UTC, okayama-daiki commented on libs/notifier/notifier.go
> +	}
7b7139e

2024-10-13 05:52 UTC, okayama-daiki commented on libs/notifier/notifier.go
> +	channelAccessToken = os.Getenv("LINE_CHANNEL_ACCESS_TOKEN")
7b7139e

2024-10-13 05:52 UTC, okayama-daiki commented on libs/notifier/notifier.go
> +}
> `init`も扱いが面倒なので`bot`を`main`packageで初期化すれば良いと思います.

7b7139e

2024-10-13 06:01 UTC, okayama-daiki commented on libs/crawler/crawler.go
> +	}
8c89cb2

2024-10-13 06:16 UTC, okayama-daiki commented on main.go
> +	targetId = os.Getenv("LINE_TARGET_ID")
a77d495

2024-10-13 06:23 UTC, okayama-daiki commented on libs/notifier/notifier.go
> +}
> それと`log.Fatal`はあまり使わない方が良いです. 明示的に`panic`を呼び出すか, `os.Exit(1)`などを使った方が良いです. https://zenn.dev/snowcrush/articles/21f28163e067cb

d74830e

2024-10-13 06:26 UTC, okayama-daiki commented on go.mod
386330f

2024-10-13 06:32 UTC, okayama-daiki commented on deploy.sh
既存のロールを使うんじゃなくて、新しいロールを作ってそれを割り当てるようにした方がいいのかもしれない、、、

2024-10-13 06:34 UTC, okayama-daiki commented on deploy.sh
元のテンプレートの方を変更する必要があるので、一旦これは無視してください。

2024-10-13 06:38 UTC, hamao0820 requested changes

2024-10-13 06:38 UTC, hamao0820 commented on main.go
>  }
`init`を使わずに`main`関数の中で定義すれば良いと思います.
`lambdaHandler`の中で`bot`などを使いたいたいなら無名関数として定義するか, `bot`などを持つ`lambda`用の構造体を作って`New`で渡せば良いと思います(こっちの方が良さそう). `main`関数内で`Start`メソッドを呼び出す形にすれば良いですね

2024-10-13 06:39 UTC, hamao0820 commented on deploy.sh
見せちゃダメなやつと思ってましたが, そうでないなら今のままで良いと思います

2024-10-13 08:58 UTC, hamao0820 commented on main.go
> +			StatusCode: 500,
`http.StatusInternalServerError`とかを使った方がいいかもですね

2024-10-13 14:14 UTC, okayama-daiki commented on main.go
>  }
e037bda

2024-10-13 14:15 UTC, okayama-daiki commented on main.go
> +			StatusCode: 500,
確かに。b060b82

2024-10-13 14:15 UTC, okayama-daiki commented on main.go
> +			StatusCode: 500,
b060b82

2024-10-13 22:23 UTC, hamao0820 reviewed
正直自分は設計とか全然したことないので正解はわからないです

2024-10-13 22:23 UTC, hamao0820 commented on main.go
>  		log.Fatal(err)
やっぱりあんまり`main`関数の中でも`log.Fatal`を使いたくないんですよねぇ
するとしたら[この記事](https://zenn.dev/snowcrush/articles/21f28163e067cb)みたいにするか(正直そんなことするのは面倒), ちょっと面倒だけど
```
if err != nil {
    log.Println(err)
    os.Exit(1)
}
```
を自分で呼び出すのが良いと思います.

2024-10-13 22:23 UTC, hamao0820 commented on main.go
>  		log.Fatal(err)
`log.Fatal`の内部実装と同じだから一緒だろと思うかも知れませんが, 呼び出し先の関数内で`os.Exit`が呼ばれると, 呼び出し元での`defer`呼ばれなかったりと細かな違いがあります.

2024-10-13 22:23 UTC, hamao0820 commented on main.go
> +	lambda.Start(handler.HandleRequest)
`lambda`packageとかにまとめて`lambda.Start`もメソッドにすればいいんじゃないかなって気もします
`handler`packageの方で`bot`とか渡して`Handler`を返すような関数を作るとか

2024-10-14 01:59 UTC, okayama-daiki commented on main.go
> +	)
[昔](https://github.com/okayama-daiki/kindle-daily-deals-notifier/blob/8c89cb267c5064af9e86f612032376dca0b0b7fb/main.go) `bot` をグローバルで宣言してたからですね。
今はもうそうする必要はないです。

2024-10-14 02:01 UTC, okayama-daiki commented on main.go
> +	)
c86c2db

2024-10-14 02:01 UTC, okayama-daiki commented on main.go
> +		bot *messaging_api.MessagingApiAPI
c86c2db

2024-10-14 02:10 UTC, okayama-daiki commented on main.go
>  		log.Fatal(err)
あー `main` 関数のロジックを丸ごと別の関数に移せって言ってるんですね。ちょっと読み違えてました😅

2024-10-14 02:53 UTC, okayama-daiki commented on main.go
>  		log.Fatal(err)
要するに明示的に書けってことですか？

> `log.Fatal`の内部実装と同じだから一緒だろと思うかも知れませんが, 呼び出し先の関数内で`os.Exit`が呼ばれると, 呼び出し元での`defer`呼ばれなかったりと細かな違いがあります.

ちょっとよく分かってないんですけど、これって `main` 関数内で `os.Exit` を呼び出しても `main` 関数内での `defer` 文は呼ばれなくなるんじゃないんですか？？

2024-10-14 02:55 UTC, hamao0820 commented on main.go
>  		log.Fatal(err)
`os.Exit`が呼び出された関数内のdeferが呼ばれた後に終了する感じだと思います

2024-10-14 02:56 UTC, hamao0820 commented on main.go
>  		log.Fatal(err)
> 要するに明示的に書けってことですか？

はい

2024-10-14 04:43 UTC, okayama-daiki commented on main.go
>  		log.Fatal(err)
72439de

2024-10-14 04:49 UTC, okayama-daiki commented on main.go
> +	lambda.Start(handler.HandleRequest)
よかったらそうすることのメリットを教えてください

2024-10-14 07:18 UTC, okayama-daiki commented on main.go
> +	lambda.Start(handler.HandleRequest)
f450535

2024-10-14 07:28 UTC, okayama-daiki commented
@hamao0820 
とても勉強になりました。ありがとうございました。

2024-10-14 07:30 UTC, merged